import { type Metadata } from 'next';
import { Home } from './_container/Home';

export default Home;

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.png' }]
};
